### PR TITLE
Fix issue 56

### PR DESCRIPTION
**Pull request by bosman81**
search/replace all occurrences of _requestedDestination with _destinationLinkName in orders/generic.py

### CODE REVIEW

**Comment by s-maheshbabu** [comment]
May be all occurrences of `requested_destination` should be replaced with `destinationLinkName` for consistency.

**Comment by bosman81** [comment]
While this is a good idea, it will break code migrated from TDA.

**Comment by alexgolec** [comment]
I'm not checking this in because until we get confirmation from schwab one way or another I hesitate to break people.

**Comment by bosman81** [comment]
Hmm... I see this is fixed in the latest code already. I am confused but the fix is in, so I am happy

**Pull request closed without merging**
